Fix panic on serial port opening failure
boardswarm/boardswarm pull request #152
Opened 2024-12-30 13:46 UTC by laeyraud

This commit prevents a panic if a serial port cannot be opened (eg permission issues).

2025-01-18 08:21 UTC, sjoerdsimons requested changes

2025-01-18 08:21 UTC, sjoerdsimons commented on boardswarm/src/serial/mod.rs
> +            let fmt_err = ConsoleError::InternalError(format!(
This isn't really an internal error; an internal error would mean something is very broken... internally  (there are probably other parts of the codebase that abuse it a bit).

while serial opens failing are often either due to the device having disappeared in the mean time (race fun), because the permissions are incorrect or something is actually wrong with the serial console.. Which could be mapped to respectively `not_found`, `unavailable` and probably `unknown` ? Though as a first step i wouldn't mind having it all map to one of those (either unavailable or unknown).

2025-01-18 08:21 UTC, sjoerdsimons commented on boardswarm/src/serial/mod.rs
> +    async fn get_writer(&self) -> Result<Arc<AsyncMutex<WriteHalf<SerialStream>>>, ConsoleError> {
```suggestion
   #[instrument(skip_all, err)]
    async fn get_writer(&self) -> Result<Arc<AsyncMutex<WriteHalf<SerialStream>>>, ConsoleError> {
```
This will automatically cause an error log to be triggered when the function returns an error

2025-01-18 08:21 UTC, sjoerdsimons commented on boardswarm/src/serial/mod.rs
> +            return Err(fmt_err);
`map_err` would likely be more elegant here

2025-01-18 08:21 UTC, sjoerdsimons commented on boardswarm/src/serial/mod.rs
> +    async fn get_reader(&self) -> Result<broadcast::Receiver<Bytes>, ConsoleError> {
same comments as get_writer :)

2025-01-19 11:18 UTC, laeyraud commented on boardswarm/src/serial/mod.rs
> +            let fmt_err = ConsoleError::InternalError(format!(
You're right, unavailable would be better in this case.
I'll replace this new InternalError value by Unavailable in ConsoleError enum and use it instead in the code.

2025-01-19 11:20 UTC, laeyraud commented on boardswarm/src/serial/mod.rs
> +    async fn get_writer(&self) -> Result<Arc<AsyncMutex<WriteHalf<SerialStream>>>, ConsoleError> {
I did not know this macro, I'll try it as it would make the new error handling more compact

2025-01-19 11:36 UTC, laeyraud commented on boardswarm/src/serial/mod.rs
> +            return Err(fmt_err);
You're right.
With the macro automatically printing the error, it allows to compact the open error handling in both get_reader and get_writer.

2025-01-19 11:38 UTC, laeyraud commented on boardswarm/src/serial/mod.rs
> +    async fn get_reader(&self) -> Result<broadcast::Receiver<Bytes>, ConsoleError> {
I'll apply the same modifications in the function.

2025-01-19 11:38 UTC, laeyraud commented
I've pushed the requested fixes and rebased the branch with latest commits from main at the same time

2025-02-23 19:22 UTC, sjoerdsimons requested changes

2025-02-23 19:22 UTC, sjoerdsimons commented on boardswarm/src/main.rs
> +                .map_err(|e| tonic::Status::internal(e.to_string()))?;
still always returns an internal error I think? Better to implement `From<ConsoleError> for tonic::Status`  similar to e.g. `VolumeError,` then you can just return the error directly.

2025-02-24 08:42 UTC, laeyraud commented on boardswarm/src/main.rs
> +                .map_err(|e| tonic::Status::internal(e.to_string()))?;
I forgot about this one (I focused on replacing the ConsoleError).
I'll apply your suggestion to convert ConsoleError to tonic::Status.

2025-04-06 06:05 UTC, sjoerdsimons approved these changes

2025-04-06 06:11 UTC, merged