Increase UI terminal size
boardswarm/boardswarm pull request #153
Opened 2024-12-31 12:02 UTC by laeyraud

This merge requests aims to improve the terminal ergonomics in UI mode (see #87).

Previously, the console terminal size  was hardcoded to 80 characters x 24 lines. Now the UI size is auto detected and resized on the fly to fit the main terminal. 
A new option "--scrollback-lines" is also added to manually configure the scrollback buffer.

2025-01-18 09:30 UTC, sjoerdsimons requested changes
fwiw #87 would only be fixed by the first commit; the latter is seperate and could be merged seperately quite easily. 

The autoresizing is more controversial as *not* using the *local* terminal size is a feature not a bug. The fundamental problem is that what we're rendering is generated by the remote with an assumed terminal size; 80x24 is the default size for both u-boot as well as the typical default for linux console hence the current suggestion.  If remote and local understanding don't match you can get weird rendering artifacs. With u-boot this even happens on the console with long lines, once in linux it mostly show up for things that aren't simply line based output.

When you're using e.g. a local shell or e.g. ssh the columns/width is kept in sync (you can override them with e.g stty). For serial it's not that obvious as we can't be guaranteed the remote side recognize escape sequences..

fwiw xterm has an extension escape to resize the *local* size with the vt100 parse we use does recognize, so resizing can be triggered from both sides.

Overall I agree with the goal of removing the hardcoded 80x24, but it needs a bit more then just doing autoresizing.. As an mvp start we could add options to configure a static size and or optionally enable auto-resizing with documented caveats

2025-01-27 09:20 UTC, laeyraud commented
> fwiw #87 would only be fixed by the first commit; the latter is seperate and could be merged seperately quite easily.
> 
> The autoresizing is more controversial as _not_ using the _local_ terminal size is a feature not a bug. The fundamental problem is that what we're rendering is generated by the remote with an assumed terminal size; 80x24 is the default size for both u-boot as well as the typical default for linux console hence the current suggestion. If remote and local understanding don't match you can get weird rendering artifacs. With u-boot this even happens on the console with long lines, once in linux it mostly show up for things that aren't simply line based output.
> 
> When you're using e.g. a local shell or e.g. ssh the columns/width is kept in sync (you can override them with e.g stty). For serial it's not that obvious as we can't be guaranteed the remote side recognize escape sequences..
> 
> fwiw xterm has an extension escape to resize the _local_ size with the vt100 parse we use does recognize, so resizing can be triggered from both sides.
> 
> Overall I agree with the goal of removing the hardcoded 80x24, but it needs a bit more then just doing autoresizing.. As an mvp start we could add options to configure a static size and or optionally enable auto-resizing with documented caveats

I've reworked the commits to add as you suggested an option to select either a fixed value or being in autoresize. 
The default behaviour would remain the terminal size being in 80x24.

2025-02-23 19:32 UTC, sjoerdsimons requested changes

2025-02-23 19:32 UTC, sjoerdsimons commented on boardswarm-cli/src/main.rs
> +        #[clap(long, default_value = "80x24")]
Any reason for tis not directly being `TerminalSizeSetting`? Also doesn't document the `auto` setting

2025-02-23 20:25 UTC, laeyraud commented on boardswarm-cli/src/main.rs
> +        #[clap(long, default_value = "80x24")]
No reason, just forgot I could use the new type directly from clap parser. 
I modified the code to use it and also reword on the help to document auto option as well

2025-04-06 14:15 UTC, sjoerdsimons commented on boardswarm-cli/src/ui.rs
> +        if let Some(size_fmt) = fmt.split_once('x') {
this is a nitpick but something like:
```rust
let (w, h) = fmt.split_once('x').ok_or(TerminalSizeSettingError::ParseError)?;
```
may be more elegant als it avoids the big if block where one case just returns an error; also unpacking tuples early is a bit more readable

2025-04-06 14:19 UTC, sjoerdsimons commented on boardswarm-cli/src/ui.rs
> +            match (size_fmt.0.parse::<u16>(), size_fmt.1.parse::<u16>()) {
If you implement `From ParseIntError for TerminalSizeSettingError` you can do quick return with `?` instead of having to do a match block here.

2025-04-06 14:21 UTC, sjoerdsimons commented on boardswarm-cli/src/ui.rs
> +                Err(_) => Size {
potentially add a warn! here about doing a fallback

2025-04-06 15:09 UTC, laeyraud commented on boardswarm-cli/src/ui.rs
> +        if let Some(size_fmt) = fmt.split_once('x') {
Fixed

2025-04-06 15:24 UTC, laeyraud commented on boardswarm-cli/src/ui.rs
> +            match (size_fmt.0.parse::<u16>(), size_fmt.1.parse::<u16>()) {
With this suggestion and the previous, it does simply a lot .

2025-04-06 15:35 UTC, laeyraud commented on boardswarm-cli/src/ui.rs
> +                Err(_) => Size {
Fixed

2025-04-06 17:52 UTC, sjoerdsimons approved these changes

2025-04-06 17:57 UTC, merged